name: Dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "18"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      - name: Start Android emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo adduser `id -un` libvirt
          sudo adduser `id -un` kvm
          sudo apt-get install -y android-sdk
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;default;x86_64"
          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -no-boot-anim -accel on &

      - name: Wait for Android emulator to finish booting
        run: |
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Run tests
        run: flutter test
